export var IDENTIFIER_TYPE;
(function (IDENTIFIER_TYPE) {
    IDENTIFIER_TYPE["EMAIL"] = "EMAIL";
    IDENTIFIER_TYPE["PHONE"] = "PHONE";
})(IDENTIFIER_TYPE || (IDENTIFIER_TYPE = {}));
export var AUTHENTICATION_METHOD;
(function (AUTHENTICATION_METHOD) {
    AUTHENTICATION_METHOD["MAGIC_LINK"] = "MAGIC_LINK";
    AUTHENTICATION_METHOD["OTP"] = "OTP";
})(AUTHENTICATION_METHOD || (AUTHENTICATION_METHOD = {}));
export var SOCIAL_LOGIN_ACTION;
(function (SOCIAL_LOGIN_ACTION) {
    SOCIAL_LOGIN_ACTION["LOGIN"] = "O_LOGIN";
    SOCIAL_LOGIN_ACTION["CONNECT"] = "O_CONNECT";
})(SOCIAL_LOGIN_ACTION || (SOCIAL_LOGIN_ACTION = {}));
//# sourceMappingURL=binder.js.map